on: 
  push:
  pull_requests:

job:
  runs-on: windows-latest
  checkRisk:
    steps:
      - name: Checkout Code
        uses: actions/checkout.py

      - name: Set-up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'

      - name: Run Python Script
        run: |
          python -m pip install
          python analyze.py


